FROM ubuntu:22.04
LABEL maintainer='Ihor Stetsiuk <stetsyukia@gmail.com>' \
      terraform_version='${TERRAFORM_VERSION}' \
      ansible_version='${ANSIBLE_VERSION}' \
      version='1.0.0'

### environment
ENV TERRAFORM_VERSION 1.9.2
ENV ANSIBLE_VERSION 2.10.7
ENV S3CMD_VERSION 2.3.0
ENV DNSCONTROL_VERSION v3.28.0

RUN export DEBIAN_FRONTEND=noninteractive \
  && apt-get update && apt-get install -yqq \
    curl \
    unzip \
    git \
    pip \
    jq \
    rsync \
    rclone \
    ca-certificates \
    gpg \
    apt-transport-https \
    pigz pbzip2 pixz \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*
###( Install kubectl and helm )###
RUN mkdir -p /etc/apt/keyrings && curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg \
    && chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg \
    && echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' > /etc/apt/sources.list.d/kubernetes.list \
    && curl -fsSL https://baltocdn.com/helm/signing.asc | apt-key --keyring /usr/share/keyrings/helm.gpg add - > /dev/null \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" > /etc/apt/sources.list.d/helm-stable-debian.list \
    && apt-get update && apt-get install -yqq \
        kubectl \
        helm \
        && apt-get clean -y && rm -rf /var/lib/apt/lists/*

###( Install terraform )###
RUN DPK_ARCH=$(dpkg --print-architecture) \
  && curl -s https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${DPK_ARCH}.zip -o /tmp/terraform_${TERRAFORM_VERSION}_linux_${DPK_ARCH}.zip \
  && unzip -qq /tmp/terraform_${TERRAFORM_VERSION}_linux_${DPK_ARCH}.zip -d /usr/local/bin
###( Install ansible )###
RUN pip install -U ansible==${ANSIBLE_VERSION} s3cmd==${S3CMD_VERSION} netaddr==1.3.0 \
  && mkdir -p /etc/ansible
###( Install dnscontrol )###
RUN curl -L https://github.com/StackExchange/dnscontrol/releases/download/${DNSCONTROL_VERSION}/dnscontrol-Linux -o /usr/local/bin/dnscontrol \
  && chmod +x /usr/local/bin/dnscontrol
###( Install google-cloud-sdk )###
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y \
    && apt-get install google-cloud-cli -y \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

COPY config/ansible-jammy.cfg /etc/ansible/ansible.cfg
