name: "Build test application for the Kubernetes learning"
run-name: ${{ github.actor }} is building k8s test app

on:
  push:
    branches:
      - "k8s-*"
    tags:
      - "k8s-v*"

env:
  OWNER: chip0k
  K8S_TEST_IMAGE_NAME: k8s-test

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=auto
            prefix=
            suffix=-v1
          images: ${{ env.OWNER }}/${{ env.K8S_TEST_IMAGE_NAME }}
      - name: Build and push Dockerfile-k8s-test
        uses: docker/build-push-action@v4
        with:
          # platforms: linux/amd64,linux/arm64
          context: ./test-app
          file: ./test-app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
