name: "CI Build docker image"
run-name: ${{ github.actor }} is building docker images

on:
  push:
    # branches:
    #   - "main"
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - '.github/**/*.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  # pull_request:
  #   branches:
  #     - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/devops-tools
      -
        name: Build and push Dockerfile-ubuntu-focal
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile-ubuntu-focal
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-tools:0.0.0-focal
      - 
        name: Build and push Dockerfile-ubuntu-jammy
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile-ubuntu-jammy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-tools:0.0.0-jammy

