name: "CI Build docker image"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Dockerfile-ubuntu-focal
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-ubuntu-focal
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-tools:0.0.0-focal
      
