name: "CI Build docker image"
run-name: ${{ github.actor }} is building docker images

on:
  push:
    branches:
      - dev-*
    tags: ["v*.*.*"]
    paths-ignore:
      - ".github/**/*.yml"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
  pull_request:

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  OWNER: chip0k
  DEVOPS_IMAGE_NAME: devops-tools

jobs:
  build-devops-tools-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=auto
            prefix=
            suffix=-alpine
          images: ${{ env.OWNER }}/${{ env.DEVOPS_IMAGE_NAME }}

      - name: Build and push Dockerfile-alpine
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./dockerfiles/Dockerfile-alpine
          push: true
          tags: ${{ steps.meta.outputs.tags }}-alpine
